<a href="https://colab.research.google.com/github/RoihansLab/Machine-Learning-Projects/blob/main/10_End_to_End_Retail_Demand_Forecasting/10_analisis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Data Analytic for 10_End_to_End_Retail_Demand_Forecasting.**

## **1. Import Library Module**

In [4]:
#for data
import pandas as pd
import numpy as np
#for visualization
import matplotlib.pyplot as plt
import seaborn as sns

### Visualized default Settings

In [5]:
plt.figure(figsize = (10,6))
sns.set(style="whitegrid")

### import dataset

In [16]:
df = pd.read_csv("/content/demand_forecasting.csv", on_bad_lines='skip')
df.head(20)

/tmp/ipykernel_2573/380996626.py:1: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/content/demand_forecasting.csv", on_bad_lines='skip')

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Price,Discount,Weather Condition,Promotion,Competitor Pricing,Seasonality,Epidemic,Demand
0,2022-01-01,S001,P0001,Electronics,North,195.0,102,252,72.72,5.0,Snowy,0.0,85.73,Winter,0.0,115.0
1,2022-01-01,S001,P0002,Clothing,North,117.0,117,249,80.16,15.0,Snowy,1.0,92.02,Winter,0.0,229.0
2,2022-01-01,S001,P0003,Clothing,North,247.0,114,612,62.94,10.0,Snowy,1.0,60.08,Winter,0.0,157.0
3,2022-01-01,S001,P0004,Electronics,North,139.0,45,102,87.63,10.0,Snowy,0.0,85.19,Winter,0.0,52.0
4,2022-01-01,S001,P0005,Groceries,North,152.0,65,271,54.41,0.0,Snowy,0.0,51.63,Winter,0.0,59.0
5,2022-01-01,S001,P0006,Toys,North,209.0,60,0,35.53,0.0,Snowy,0.0,40.01,Winter,0.0,55.0
6,2022-01-01,S001,P0007,Groceries,North,118.0,81,335,23.27,5.0,Snowy,0.0,24.78,Winter,0.0,94.0
7,2022-01-01,S001,P0008,Electronics,North,244.0,42,0,37.79,5.0,Snowy,0.0,44.85,Winter,0.0,61.0
8,2022-01-01,S001,P0009,Clothing,North,115.0,88,139,94.20,5.0,Snowy,0.0,108.70,Winter,0.0,129.0
9,2022-01-01,S001,P0010,Furniture,North,192.0,70,300,113.35,10.0,Snowy,0.0,129.98,Winter,0.0,69.0
10,2022-01-01,S001,P0011,Furniture,North,215.0,51,142,156.34,0.0,Snowy,0.0,188.96,Winter,0.0,64.0
11,2022-01-01,S001,P0012,Groceries,North,289.0,121,215,84.48,0.0,Snowy,0.0,92.02,Winter,0.0,104.0
12,2022-01-01,S001,P0013,Toys,North,279.0,113,0,33.10,5.0,Snowy,0.0,39.11,Winter,0.0,110.0
13,2022-01-01,S001,P0014,Groceries,North,252.0,121,479,80.13,10.0,Snowy,1.0,92.24,Winter,0.0,165.0
14,2022-01-01,S001,P0015,Toys,North,119.0,55,74,14.39,5.0,Snowy,0.0,13.59,Winter,0.0,64.0
15,2022-01-01,S001,P0016,Groceries,North,103.0,78,372,38.79,10.0,Snowy,0.0,35.14,Winter,0.0,115.0
16,2022-01-01,S001,P0017,Toys,North,128.0,59,0,21.21,0.0,Snowy,0.0,22.73,Winter,0.0,75.0
17,2022-01-01,S001,P0018,Groceries,North,281.0,78,0,54.40,5.0,Snowy,0.0,54.10,Winter,0.0,66.0
18,2022-01-01,S001,P0019,Furniture,North,281.0,61,0,95.56,10.0,Snowy,0.0,103.05,Winter,0.0,58.0
19,2022-01-01,S001,P0020,Furniture,North,266.0,36,0,100.47,5.0,Snowy,0.0,115.24,Winter,0.0,43.0

In [19]:
print(df.dtypes)

Date                   object
Store ID               object
Product ID             object
Category               object
Region                 object
Inventory Level       float64
Units Sold             object
Units Ordered           int64
Price                 float64
Discount              float64
Weather Condition      object
Promotion             float64
Competitor Pricing    float64
Seasonality            object
Epidemic              float64
Demand                float64
dtype: object

In [20]:
df["Date"] = pd.to_datetime(df["Date"])

In [21]:
print(df.dtypes)

Date                  datetime64[ns]
Store ID                      object
Product ID                    object
Category                      object
Region                        object
Inventory Level              float64
Units Sold                    object
Units Ordered                  int64
Price                        float64
Discount                     float64
Weather Condition             object
Promotion                    float64
Competitor Pricing           float64
Seasonality                   object
Epidemic                     float64
Demand                       float64
dtype: object

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50856 entries, 0 to 50855
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                50856 non-null  datetime64[ns]
 1   Store ID            50856 non-null  object
 2   Product ID          50856 non-null  object
 3   Category            50856 non-null  object
 4   Region              50856 non-null  object
 5   Inventory Level     50856 non-null  float64
 6   Units Sold          50856 non-null  object
 7   Units Ordered       50856 non-null  int64
 8   Price               50856 non-null  float64
 9   Discount            50855 non-null  float64
 10  Weather Condition   50855 non-null  object
 11  Promotion           50855 non-null  float64
 12  Competitor Pricing  50855 non-null  float64
 13  Seasonality         50855 non-null  object
 14  Epidemic            50855 non-null  float64
 15  Demand              50855 non-null  float64
dtypes: datetime64[ns](1), float64(7), int64(1), object(7)
memory usage: 6.2+ MB

In [24]:
df.duplicated().sum()

np.int64(0)

In [25]:
df.describe().T

,count,mean,min,25%,50%,75%,max,std
Date,50856,2023-01-17 02:15:47.994337024,2022-01-01 00:00:00,2022-05-08 00:00:00,2023-05-21 00:00:00,2023-09-25 00:00:00,2024-01-30 00:00:00,NaN
Inventory Level,50856.0,305.628824,0.0,137.0,230.0,415.0,2267.0,230.390153
Units Ordered,50856.0,90.686015,0.0,0.0,0.0,123.0,1616.0,165.488989
Price,50856.0,68.078788,4.74,32.1475,64.91,96.3,228.03,39.498113
Discount,50855.0,9.079343,0.0,5.0,10.0,10.0,25.0,7.473745
Promotion,50855.0,0.327618,0.0,0.0,0.0,1.0,1.0,0.469349
Competitor Pricing,50855.0,69.832602,4.29,32.805,66.15,98.445,261.22,41.08716
Epidemic,50855.0,0.176954,0.0,0.0,0.0,0.0,1.0,0.381634
Demand,50855.0,106.162088,4.0,73.0,101.0,135.0,430.0,47.85376