<a href="https://colab.research.google.com/github/RoihansLab/Machine-Learning-Projects/blob/main/10_End_to_End_Retail_Demand_Forecasting/10_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **1. Import Libraries Module**

In [22]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

from xgboost import XGBRegressor

import pickle

## **2. Load the Datasets**

In [23]:
df = pd.read_csv("/content/demand_forecasting.csv")
df

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Price,Discount,Weather Condition,Promotion,Competitor Pricing,Seasonality,Epidemic,Demand
0,2022-01-01,S001,P0001,Electronics,North,195,102,252,72.72,5,Snowy,0,85.73,Winter,0,115
1,2022-01-01,S001,P0002,Clothing,North,117,117,249,80.16,15,Snowy,1,92.02,Winter,0,229
2,2022-01-01,S001,P0003,Clothing,North,247,114,612,62.94,10,Snowy,1,60.08,Winter,0,157
3,2022-01-01,S001,P0004,Electronics,North,139,45,102,87.63,10,Snowy,0,85.19,Winter,0,52
4,2022-01-01,S001,P0005,Groceries,North,152,65,271,54.41,0,Snowy,0,51.63,Winter,0,59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75995,2024-01-30,S005,P0016,Toys,North,233,63,0,29.80,5,Snowy,0,32.23,Winter,0,64
75996,2024-01-30,S005,P0017,Toys,North,137,115,141,42.92,5,Snowy,0,40.73,Winter,0,137
75997,2024-01-30,S005,P0018,Clothing,North,197,44,0,17.81,10,Snowy,0,19.41,Winter,0,68
75998,2024-01-30,S005,P0019,Furniture,North,125,58,0,151.72,0,Snowy,0,143.71,Winter,0,84
75999,2024-01-30,S005,P0020,Toys,North,126,63,59,25.78,10,Snowy,0,29.32,Winter,0,73

In [24]:
df.columns

Index(['Date', 'Store ID', 'Product ID', 'Category', 'Region',
       'Inventory Level', 'Units Sold', 'Units Ordered', 'Price', 'Discount',
       'Weather Condition', 'Promotion', 'Competitor Pricing', 'Seasonality',
       'Epidemic', 'Demand'],
      dtype='object')

In [35]:
feature = [
    "Price",
    "Competitor Pricing",
    "Discount",
    "Inventory Level",
    "Category",
    "Promotion"
]

feature

['Price',
 'Competitor Pricing',
 'Discount',
 'Inventory Level',
 'Category',
 'Promotion']

In [36]:
feature

['Price',
 'Competitor Pricing',
 'Discount',
 'Inventory Level',
 'Category',
 'Promotion']

In [37]:
target = "Demand"

In [40]:
x = df[feature].copy()
x

,Price,Competitor Pricing,Discount,Inventory Level,Category,Promotion
0,72.72,85.73,5,195,Electronics,0
1,80.16,92.02,15,117,Clothing,1
2,62.94,60.08,10,247,Clothing,1
3,87.63,85.19,10,139,Electronics,0
4,54.41,51.63,0,152,Groceries,0
...,...,...,...,...,...,...
75995,29.80,32.23,5,233,Toys,0
75996,42.92,40.73,5,137,Toys,0
75997,17.81,19.41,10,197,Clothing,0
75998,151.72,143.71,0,125,Furniture,0
75999,25.78,29.32,10,126,Toys,0

In [42]:
y = df[target]
y

0        115
1        229
2        157
3         52
4         59
        ...
75995     64
75996    137
75997     68
75998     84
75999     73
Name: Demand, Length: 76000, dtype: int64