<a href="https://colab.research.google.com/github/RoihansLab/Machine-Learning-Projects/blob/main/06_hyperparameter_tuning_Random_Forest/hyperparameter_tuning_Random_Forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Hyperparametets for Machine Learning Model**

## **1. Make Syntetic Datasets**

### **1.1. Generate The Datasets**

In [80]:
from sklearn.datasets import make_classification

X ,y = make_classification(n_samples=200, n_redundant=0, n_classes=2, n_features=10, random_state=42)

### **1.2. Examine Data Dimension**

In [81]:
X.shape, y.shape

((200, 10), (200,))

In [82]:
import pandas as pd

In [83]:
import pandas as pd
pd.DataFrame(X)

            0         1         2  ...         7         8         9
0   -1.065114  0.280920  0.529693  ... -0.609512 -0.305225  0.010353
1   -0.546244  0.040911  0.579291  ... -1.478912  0.391804 -0.576510
2    0.342725 -1.810057  1.329153  ...  0.569767  0.456753 -0.082151
3    0.179894 -2.103379  0.940771  ...  0.918317  1.392002 -0.988591
4    0.413435  0.505716  1.496044  ... -0.773789  1.876796  0.869606
..        ...       ...       ...  ...       ...       ...       ...
195  1.066675 -1.408241  0.146714  ...  1.382159  1.169296  0.820482
196 -0.763259 -0.638870 -0.904317  ... -1.627542 -1.804882 -0.662624
197 -1.062394  0.762274  2.589564  ... -0.187144  0.428307 -0.079641
198 -0.019420  0.186413 -1.067803  ...  0.799942 -0.303180 -0.223466
199 -0.098588  0.091482  0.287124  ...  0.708214  0.018850 -1.090399

[200 rows x 10 columns]

In [84]:
pd.DataFrame(y)

     0
0    0
1    0
2    1
3    1
4    0
..  ..
195  1
196  0
197  1
198  1
199  1

[200 rows x 1 columns]

# **2. Data Split(80/20)**

### **2.1 Data Split**

ratio for testing = 20%
ration for training = 80%

In [85]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

### **2.2. Examine Data Dimension**

#### **2.2.1 Examine Data Train Dimension**

as we can see the training sets in X variable has 160 row with 10 column for the X while there are 160 row with 1 column in y variable

In [86]:
X_train.shape, y_train.shape

((160, 10), (160,))

#### **2.2.2 Examine Data Test Dimension**

the testing sets has 40 rows and 10 column in X variable and 40 rows in 1 column y yvariable

In [87]:
X_test.shape, y_test.shape

((40, 10), (40,))

## **3. Building a Simple Machine Learning Model with Random Forest**

In [88]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

rf = RandomForestClassifier(n_estimators=100, max_features=100)

In [89]:
rf.fit(X_train, y_train)

RandomForestClassifier(max_features=100)

In [90]:
rf.score(X_test, y_test)

0.85

In [91]:
y_pred = rf.predict(X_test)

In [92]:
accuracy_score(y_pred, y_test)

0.85

In [93]:
y_pred, y_test

(array([1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
        0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0]),
 array([1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
        0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0]))

## **4. Hyperparametet Tuning**

now i will be performing of the tuning of hyperparamaters of RandomForestClassifier model. The hyperparameters that we will tune includes max_features and n_estimators

In [94]:
from sklearn.model_selection import GridSearchCV
import numpy as np

max_features_range = np.arange(1,6,1)
n_estimators_range = np.arange(10,210,10)
param_grid = dict(max_features=max_features_range, n_estimators=n_estimators_range)

rf = RandomForestClassifier()

grid = GridSearchCV(estimator=rf, param_grid=param_grid, cv=5)

In [95]:
grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'max_features': array([1, 2, 3, 4, 5]),
                         'n_estimators': array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190, 200])})

In [96]:
print("The best parameters are %s with a score of %0.2f"
% (grid.best_params_, grid.best_score_))

The best parameters are {'max_features': np.int64(2), 'n_estimators': np.int64(160)} with a score of 0.86

## **5. Data Frame of Grid Search parameters and their Accuracy Scores**

In [97]:
import pandas as pd

grid_results = pd.concat([pd.DataFrame(grid.cv_results_["params"]), pd.DataFrame(grid.cv_results_["mean_test_score"], columns=["Accuracy"])], axis=1)

grid_results

    max_features  n_estimators  Accuracy
0              1            10   0.66250
1              1            20   0.73125
2              1            30   0.80625
3              1            40   0.79375
4              1            50   0.77500
..           ...           ...       ...
95             5           160   0.81250
96             5           170   0.82500
97             5           180   0.81250
98             5           190   0.82500
99             5           200   0.83125

[100 rows x 3 columns]

## **6. Preparing data for making contour plots**

prior to making contour plots, we will have to reshape the data into compatible that will be recognized by th contour plot functions.

I'll be using pandas groupby() function to segment the data into groups based on 2 parameters: max_features and n_enstimators

In [105]:
grid_contour = grid_results.groupby(['max_features', 'n_estimators']).mean()
grid_contour

                           Accuracy
max_features n_estimators
1            10             0.66250
             20             0.73125
             30             0.80625
             40             0.79375
             50             0.77500
...                             ...
5            160            0.81250
             170            0.82500
             180            0.81250
             190            0.82500
             200            0.83125

[100 rows x 1 columns]

### **Pivoting the data**

Data is reshape by pivoting the data into an m matrix where rows and columns correspond to the max_features and n_estimators, respectively

In [114]:
grid_reset = grid_contour.reset_index()
grid_reset.columns = ['max_features', 'n_estimators', 'Accuracy']
grid_pivot = grid_reset.pivot(index='max_features', columns='n_estimators', values='Accuracy')
grid_pivot

n_estimators      10       20       30   ...      180      190      200
max_features                             ...
1             0.66250  0.73125  0.80625  ...  0.77500  0.77500  0.80000
2             0.74375  0.80000  0.84375  ...  0.84375  0.85000  0.84375
3             0.80000  0.80000  0.81250  ...  0.83750  0.83125  0.83125
4             0.83125  0.80625  0.81875  ...  0.82500  0.83750  0.83750
5             0.83125  0.81875  0.81250  ...  0.81250  0.82500  0.83125

[5 rows x 20 columns]

I assign the pivoted data into the perspective x, y and z

In [116]:
x = grid_pivot.columns.values
y = grid_pivot.index.values
z = grid_pivot.values

In [117]:
x, y, z

(array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
        140, 150, 160, 170, 180, 190, 200]),
 array([1, 2, 3, 4, 5]),
 array([[0.6625 , 0.73125, 0.80625, 0.79375, 0.775  , 0.79375, 0.79375,
         0.80625, 0.79375, 0.80625, 0.80625, 0.80625, 0.79375, 0.81875,
         0.80625, 0.8125 , 0.8375 , 0.775  , 0.775  , 0.8    ],
        [0.74375, 0.8    , 0.84375, 0.83125, 0.8    , 0.8375 , 0.85   ,
         0.81875, 0.8375 , 0.83125, 0.8375 , 0.85625, 0.85625, 0.83125,
         0.825  , 0.8625 , 0.8375 , 0.84375, 0.85   , 0.84375],
        [0.8    , 0.8    , 0.8125 , 0.83125, 0.84375, 0.825  , 0.81875,
         0.83125, 0.8375 , 0.825  , 0.84375, 0.8375 , 0.83125, 0.8375 ,
         0.83125, 0.84375, 0.8375 , 0.8375 , 0.83125, 0.83125],
        [0.83125, 0.80625, 0.81875, 0.8375 , 0.83125, 0.83125, 0.83125,
         0.8375 , 0.825  , 0.84375, 0.8375 , 0.8375 , 0.8375 , 0.8375 ,
         0.83125, 0.83125, 0.83125, 0.825  , 0.8375 , 0.8375 ],
        [0.83125, 0.81875, 0.8125 , 0.83125, 0.80625, 0.825  , 0.825  ,
         0.825  , 0.825  , 0.8125 , 0.81875, 0.825  , 0.825  , 0.81875,
         0.81875, 0.8125 , 0.825  , 0.8125 , 0.825  , 0.83125]]))

### **2D Contour Plot**

visualizing the landscape of the 2 hyperparameters that we are tuning and their influence on the accuracy

In [121]:
import plotly.graph_objects as go

# Pakai go.Layout (L besar) dan dict() biar jauh lebih simpel!
layout = go.Layout(
    xaxis=dict(title='max_features'),
    yaxis=dict(title='n_estimators')
)

# Pakai go.Figure (F besar)
fig = go.Figure(data=[go.Contour(z=z, x=x, y=y)], layout=layout)

fig.update_layout(title='Hyperparameter tuning', autosize=False, width=500, height=500, margin=dict(l=65, r=50, b=65, t=90))

fig.show()

### **3D Surface Plot**

In [122]:
import plotly.graph_objects as go

fig = go.Figure(data=[go.Surface(z=z, y=y, x=x)], layout=layout)

fig.update_layout(title='Hyperparameter tuning',
                  scene=dict(
                      xaxis_title='max_features',
                      yaxis_title='n_estimators',
                      zaxis_title='Accuracy'
                  ),
                  autosize=False,
                  width=500,
                  height=500,
                  margin=dict(l=65, r=50, b=65, t=90))

fig.show()